version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable:
        - shadow

  exclusions:
    rules:
      # Ignore test files for some linters
      - path: _test\.go
        linters:
          - errcheck
          - unparam
      # Ignore generated files
      - path: gen/
        linters:
          - all

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true
